version: "3.3"
services:
  service1:
    image: httpd
    ports: 
      - "8888:9999"
    volumes:
      - my-volume:/usr/local/apache2
    networks:
      - my-network
  service2:
    image: httpd
    volumes:
      - my-volume
    networks:
      - my-network
volumes:
  my-volume:
networks:
  my-network:

